version: '3.9'
services:
  web:
    image: python:3.9
    container_name: lacrei_web
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "poetry install && poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: lacrei_db
    environment:
      POSTGRES_DB: lacrei_db
      POSTGRES_USER: lacrei_user
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
