# Generated by Django 5.1.6 on 2025-02-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consulta", "0002_remove_consulta_data_consulta_data_consulta"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="consulta",
            table="consulta",
        ),
    ]
