# Generated by Django 5.1.6 on 2025-02-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='profissional_contato',
            new_name='contato',
        ),
        migrations.RenameField(
            model_name='profissional',
            old_name='profissional_endereco',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='profissional',
            old_name='profissional_nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='profissional',
            old_name='profissional_nome_social',
            new_name='nome_social',
        ),
        migrations.RenameField(
            model_name='profissional',
            old_name='profissional_profissao',
            new_name='profissao',
        ),
    ]
