# Generated by Django 5.1.6 on 2025-02-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profissional", "0003_alter_profissional_contato"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="profissional",
            table="profissional",
        ),
    ]
